spring.application.name=food-service 

server.port=9004
server.address=0.0.0.0

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FoodDB;encrypt=true;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=sapassword

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FoodDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
