# Tên ?ng d?ng
spring.application.name=database_food_delivery

# DataSource Configuration (MariaDB)
spring.datasource.url=jdbc:mariadb://localhost:3306/shop_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sapassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JDBC Template settings
spring.sql.init.mode=always

# JPA Configuration (n?u dùng JPA cho entity khác)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Server port
server.port=8080